#include <iostream>
#include <vector>
#include <string>
#include "vcpu.cpp"

using namespace std;

int main() {
    try {
        CPU cpu;
        
        vector<string> io_isolation_test = {
            "# I/O Port Isolation Test",
            "",
            "# ============================================",
            "# Test 1: Basic I/O in kernel mode",
            "# ============================================",
            "PRINT \"Test 1: Kernel mode I/O access\"",
            "",
            "# Write to COM1 data port",
            "LPUT 0x41 r8_0    # 'A'",
            "OUT r8_0 0x3F8",
            "PRINT \"Wrote 'A' to COM1 (0x3F8)\"",
            "",
            "# Write to keyboard data port",
            "LPUT 0x1C r8_0    # Scancode for 'A'",
            "OUT r8_0 0x60",
            "PRINT \"Wrote scancode to keyboard (0x60)\"",
            "",
            "# Read from timer",
            "IN 0x40 r8_1",
            "PRINT \"Read from PIT channel 0:\"",
            "PRINT r8_1",
            "",
            "# 16-bit I/O",
            "HPUT 0x1234 r16_0",
            "OUTW r16_0 0x40",
            "PRINT \"Wrote 0x1234 to port 0x40 (16-bit)\"",
            "",
            "INW 0x40 r16_1",
            "PRINT \"Read back:\"",
            "PRINT r16_1",
            "",
            "PRINT \"\"",
            "",
            "# ============================================",
            "# Test 2: I/O privilege level enforcement",
            "# ============================================",
            "PRINT \"Test 2: I/O privilege level (IOPL)\"",
            "",
            "SETIOPL 0         # Only CPL 0 can do I/O",
            "PRINT \"Set IOPL=0 (only kernel can do I/O)\"",
            "",
            "# This works in kernel mode",
            "OUT 0x42 0x3F8",
            "PRINT \"Kernel (CPL=0) can access all ports\"",
            "",
            "PRINT \"NOTE: User mode (CPL=3) would be blocked\"",
            "",
            "PRINT \"\"",
            "",
            "# ============================================",
            "# Test 3: I/O permission bitmap",
            "# ============================================",
            "PRINT \"Test 3: I/O Permission Bitmap\"",
            "",
            "# Enable bitmap",
            "ENABLEIOMAP",
            "PRINT \"I/O permission bitmap enabled\"",
            "",
            "# Deny COM1 port",
            "IODENY 0x3F8",
            "PRINT \"Denied access to port 0x3F8 (COM1)\"",
            "",
            "# Allow keyboard port",
            "IOALLOW 0x60",
            "PRINT \"Allowed access to port 0x60 (keyboard)\"",
            "",
            "# Allow timer ports",
            "IOALLOW 0x40",
            "IOALLOW 0x41",
            "IOALLOW 0x42",
            "PRINT \"Allowed access to ports 0x40-0x42 (timer)\"",
            "",
            "# Kernel can still access denied ports (CPL=0 bypasses bitmap)",
            "PRINT \"Kernel (CPL=0) accessing denied port 0x3F8...\"",
            "OUT 0x99 0x3F8",
            "PRINT \"Success! Kernel bypasses bitmap restrictions\"",
            "",
            "PRINT \"\"",
            "",
            "# ============================================",
            "# Test 4: Port range configuration",
            "# ============================================",
            "PRINT \"Test 4: Configuring port ranges\"",
            "",
            "# Deny serial port range 0x3F8-0x3FF",
            "PRINT \"Denying serial ports 0x3F8-0x3FF...\"",
            "HPUT 0x3F8 r16_2",
            "deny_serial:",
            "    IODENY r16_2",
            "    HUADD 1 r16_2",
            "    HCMP 0x400 r16_2",
            "    JL deny_serial",
            "",
            "PRINT \"Serial port range 0x3F8-0x3FF denied\"",
            "",
            "# Allow parallel port range",
            "IOALLOW 0x378",
            "IOALLOW 0x379",
            "IOALLOW 0x37A",
            "PRINT \"Parallel ports 0x378-0x37A allowed\"",
            "",
            "PRINT \"\"",
            "",
            "# ============================================",
            "# Test 5: Read and write to allowed ports",
            "# ============================================",
            "PRINT \"Test 5: Accessing allowed ports\"",
            "",
            "# Write to allowed keyboard port",
            "OUT 0x1E 0x60",
            "PRINT \"Wrote scancode 0x1E to keyboard port\"",
            "",
            "# Read from allowed timer port",
            "IN 0x40 r8_2",
            "PRINT \"Read from timer port 0x40\"",
            "",
            "# Write to allowed parallel port",
            "OUT 0xAA 0x378",
            "PRINT \"Wrote 0xAA to parallel port data\"",
            "",
            "# Read it back",
            "IN 0x378 r8_3",
            "PRINT \"Read back from parallel port:\"",
            "PRINT r8_3",
            "",
            "PRINT \"\"",
            "",
            "# ============================================",
            "# Test 6: Dynamic permission changes",
            "# ============================================",
            "PRINT \"Test 6: Dynamic permission changes\"",
            "",
            "# Start with custom port allowed",
            "IOALLOW 0x200",
            "PRINT \"Port 0x200 allowed\"",
            "",
            "# Use it",
            "OUT 0xBB 0x200",
            "IN 0x200 r8_4",
            "PRINT \"Wrote and read from port 0x200\"",
            "",
            "# Revoke access",
            "IODENY 0x200",
            "PRINT \"Port 0x200 access revoked\"",
            "",
            "# Kernel can still use it",
            "OUT 0xCC 0x200",
            "PRINT \"Kernel still accessed port 0x200 (bypasses bitmap)\"",
            "",
            "PRINT \"NOTE: Non-kernel CPL would be blocked\"",
            "",
            "PRINT \"\"",
            "",
            "# ============================================",
            "# Test 7: Disable and re-enable protection",
            "# ============================================",
            "PRINT \"Test 7: Disable/enable protection cycle\"",
            "",
            "DISABLEIOMAP",
            "PRINT \"I/O permission bitmap disabled\"",
            "",
            "# Now denied ports work without restriction",
            "OUT 0xDD 0x3F8",
            "PRINT \"Wrote to 0x3F8 (was denied, now unrestricted)\"",
            "",
            "# Re-enable",
            "ENABLEIOMAP",
            "PRINT \"I/O permission bitmap re-enabled\"",
            "",
            "# Denied ports are denied again (but kernel still bypasses)",
            "OUT 0xEE 0x3F8",
            "PRINT \"Kernel still accesses 0x3F8 (bypasses re-enabled bitmap)\"",
            "",
            "PRINT \"\"",
            "",
            "# ============================================",
            "# Test 8: IOPL levels",
            "# ============================================",
            "PRINT \"Test 8: Different IOPL settings\"",
            "",
            "SETIOPL 0",
            "PRINT \"IOPL=0: Only CPL 0 can do I/O\"",
            "OUT 0x11 0x40",
            "PRINT \"CPL 0 succeeded\"",
            "",
            "SETIOPL 1",
            "PRINT \"IOPL=1: CPL 0-1 can do I/O\"",
            "OUT 0x22 0x40",
            "PRINT \"CPL 0 succeeded\"",
            "",
            "SETIOPL 2",
            "PRINT \"IOPL=2: CPL 0-2 can do I/O\"",
            "OUT 0x33 0x40",
            "PRINT \"CPL 0 succeeded\"",
            "",
            "SETIOPL 3",
            "PRINT \"IOPL=3: All CPLs can do I/O\"",
            "OUT 0x44 0x40",
            "PRINT \"CPL 0 succeeded\"",
            "",
            "PRINT \"\"",
            "",
            "# ============================================",
            "# Test 9: Multiple port operations",
            "# ============================================",
            "PRINT \"Test 9: Bulk I/O operations\"",
            "",
            "# Write sequence to timer ports",
            "PRINT \"Writing sequence to timer channels...\"",
            "OUT 0x10 0x40",
            "OUT 0x20 0x41",
            "OUT 0x30 0x42",
            "",
            "# Read them back",
            "IN 0x40 r8_5",
            "IN 0x41 r8_6",
            "IN 0x42 r8_7",
            "",
            "PRINT \"Read timer channel 0:\"",
            "PRINT r8_5",
            "PRINT \"Read timer channel 1:\"",
            "PRINT r8_6",
            "PRINT \"Read timer channel 2:\"",
            "PRINT r8_7",
            "",
            "PRINT \"\"",
            "",
            "# ============================================",
            "# Test 10: Final verification",
            "# ============================================",
            "PRINT \"Test 10: Final bitmap verification\"",
            "",
            "# Set up specific allowed/denied ports",
            "DISABLEIOMAP",
            "ENABLEIOMAP",
            "",
            "IOALLOW 0x100",
            "IOALLOW 0x101",
            "IODENY 0x102",
            "IODENY 0x103",
            "",
            "PRINT \"Configured bitmap: 0x100-0x101 allowed, 0x102-0x103 denied\"",
            "",
            "# Test allowed",
            "OUT 0xA1 0x100",
            "OUT 0xA2 0x101",
            "IN 0x100 r8_8",
            "IN 0x101 r8_9",
            "",
            "PRINT \"Successfully accessed allowed ports 0x100-0x101\"",
            "PRINT \"Port 0x100 value:\"",
            "PRINT r8_8",
            "PRINT \"Port 0x101 value:\"",
            "PRINT r8_9",
            "",
            "# Kernel can access denied (but non-kernel would be blocked)",
            "OUT 0xB1 0x102",
            "OUT 0xB2 0x103",
            "PRINT \"Kernel accessed denied ports 0x102-0x103 (bypass)\"",
            "",
            "PRINT \"\"",
            "PRINT \"=== All I/O isolation tests completed successfully! ===\"",
            "",
            "# Summary",
            "PRINT \"\"",
            "PRINT \"Summary of tested features:\"",
            "PRINT \"  [✓] Basic I/O operations (IN/OUT/INW/OUTW)\"",
            "PRINT \"  [✓] I/O Privilege Level (IOPL) configuration\"",
            "PRINT \"  [✓] I/O Permission Bitmap (fine-grained control)\"",
            "PRINT \"  [✓] Port range allow/deny\"",
            "PRINT \"  [✓] Dynamic permission changes\"",
            "PRINT \"  [✓] Enable/disable protection\"",
            "PRINT \"  [✓] Kernel bypass (CPL=0)\"",
            "PRINT \"  [✓] Multiple IOPL levels\"",
            "PRINT \"  [✓] Bulk I/O operations\"",
            "PRINT \"  [✓] Bitmap verification\"",
            "",
            "QUIT",
        };
        
        cpu.load_program_lines(io_isolation_test);
        cpu.run();
        
        cout << "\n=== Test completed successfully! ===\n";
        
    } catch (const exception& e) {
        cerr << "Error: " << e.what() << endl;
        return 1;
    }
    
    return 0;
}